theme: jekyll-theme-minimal
title: Johannes Gessner
description: PhD Student in Economics
logo: https://media-exp2.licdn.com/dms/image/C5603AQGFwOf0HNtHWg/profile-displayphoto-shrink_800_800/0/1554016467479?e=1661385600&v=beta&t=t9yqesmoBXaG-lkldDUeotRX1NuXB3N2nkDnALxWtP4
show_downloads: false